"""add email column

Revision ID: e2fc229fd63b
Revises: d69bce8ee7b8
Create Date: 2026-05-05 15:15:53.631660

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2fc229fd63b'
down_revision: Union[str, Sequence[str], None] = 'd69bce8ee7b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Students', sa.Column('email', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Students', 'email')
    # ### end Alembic commands ###
